# FPS = 10
ID = "Vehicle_ID"
FRAME = "Frame_ID"
TOTAL_FRAME = "Total_Frames"
GLOBAL_TIME = "Global_Time"
X = "Local_X" # front of vehicle.feet
Y = "Local_Y" # center of vehicle,feet
GLOBAL_X = "Global_X"
GLOBAL_Y = "Global_Y"
WIDTH = "v_length" # feet
HEIGHT = "v_Width" #feet
CLASS = "v_Class" #1: motorcycle, 2: auto, 3: truck 
VELOCITY = "v_VEL" #feet/s
ACCELERATION = "v_Acc" # feet/s^2
LANE_ID = "Lane_ID"# 1: farthest left (High speed), 5: farthest right(Low Speed)  
PRECEDING_ID = "Preceding"# 0 means no vehicle
FOLLOWING_ID = "Following" # 0 means no vehicle
LOCATION = "Location" 
O_ZONE = "O_Zone"
D_ZONE = "D_Zone"
INT_ID = "Int_ID"
SECTION_ID = "Section_ID"
DIRECTION = "Direction"
MOVEMENT = "Movement"
DHW = "Space_Headway" # Distance from the front-centere of a vehicle to the fron-center of the preceding
THW = "Time_Headway" # A value of 9999.99 means vehicle speed is zero